# Generated by Django 3.1 on 2020-12-30 03:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_name', models.CharField(max_length=200)),
                ('employee_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999), django.core.validators.MinValueValidator(10000000)])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
