# Generated by Django 3.1 on 2020-12-28 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20201228_0631'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSearch',
            fields=[
                ('search_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999), django.core.validators.MinValueValidator(10000000)])),
            ],
        ),
    ]
